### ISSUE TITLE
Incorrect python dependency for skorch v0.14.0

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/skorch-feedstock#16]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

skorch v0.14.0 has removed support for Python 3.7.  However, this package on conda-forge still has python >=3.7 as a dependency.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by dhirschfeld** [comment]
> skorch v0.14.0 has removed support for Python 3.7. However, this package on conda-forge still has python >=3.7 as a dependency.

If you want issues resolved quickly GitHub lets you provide links which will render the source in the issue. Failing that, a maintainer will have to manually search the source to verify your claims, which all takes time. Unfortunately, I don't have time to manually investigate myself right now...

**Comment by BenjaminBossan** [comment]
I made #18 which I hope will resolve the issue, but I would need to a review to be sure it does.

**Comment by dhirschfeld** [comment]
> If you want issues resolved quickly GitHub lets you provide links which will render the source in the issue.

***xref:*** https://github.com/skorch-dev/skorch/blame/v0.14.0/setup.py#L13
